name: CI/CD pipeline to Docker Hub and AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/prediccion-emociones:latest .

      - name: Docker push to Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/prediccion-emociones:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker stop prediccion-emociones || true
            docker rm prediccion-emociones || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/prediccion-emociones:latest
            docker run -d --name prediccion-emociones -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/prediccion-emociones:latest
